os:
  - linux

addons:
  apt:
    packages:
      - lftp

language: php

before_install:
  - docker-compose up -d --build
  - ".travis/wait-for-container-startup.sh"

script:
  - docker-compose exec qualix vendor/bin/phpunit
  - sudo git clean -qfdx storage/logs
  - docker-compose run e2e run

before_deploy:
  - docker-compose run --entrypoint "/bin/sh -c 'php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan view:clear && rm -f storage/framework/sessions/*'" qualix

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|deploy-gryfensee|deploy-gloggi)$
