name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: docker-compose up -d qualix db node mail

      - uses: ./.github/actions/wait-for-container-startup

      - run: docker-compose exec -T qualix vendor/bin/phpunit

  frontend-tests:
    name: "Frontend tests"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: docker-compose up -d qualix db node mail

      - uses: ./.github/actions/wait-for-container-startup

      - run: docker-compose exec -T node npm run test

  e2e-tests:
    name: "End-to-end tests"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: docker-compose up -d qualix db node mail e2e-mocks

      - uses: ./.github/actions/wait-for-container-startup

      - run: docker-compose run e2e run

  ci-passed-event:
    name: "Send out CI success event"
    if: ${{ github.event_name == 'push' }}
    needs:
      - unit-tests
      - frontend-tests
      - e2e-tests
    runs-on: ubuntu-latest
    steps:

      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: ci-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
