name: Nightly

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  sync-deploy-branch:
    name: 'Sync current master to the deploy branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: repo-sync/github-sync@v2
        with:
          source_repo: 'gloggi/qualix'
          source_branch: 'master'
          destination_branch: 'deploy-prod'
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
